---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm
 
steps:
 - name: build
   image: alpinelinux/docker-cli
   volumes:
   - name: dockersock
     path: /var/run
   commands:
     - docker build - < Dockerfile.arm

volumes:
- name: dockersock
  temp: {}
  
trigger:
  branch:
  - arm
